# Generated by Django 5.2.5 on 2025-08-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tryon", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tryonrequest",
            name="body_mask",
            field=models.ImageField(blank=True, null=True, upload_to="outputs/masks/"),
        ),
        migrations.AddField(
            model_name="tryonrequest",
            name="cloth_image",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/cloth/"),
        ),
        migrations.AddField(
            model_name="tryonrequest",
            name="cloth_mask",
            field=models.ImageField(
                blank=True, null=True, upload_to="uploads/cloth_mask/"
            ),
        ),
        migrations.AddField(
            model_name="tryonrequest",
            name="generate_from_prompt",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tryonrequest",
            name="pose_json",
            field=models.FileField(blank=True, null=True, upload_to="outputs/pose/"),
        ),
    ]
