# Generated by Django 5.2.5 on 2025-08-16 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tryon", "0002_tryonrequest_body_mask_tryonrequest_cloth_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tryonrequest",
            name="prompt",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
