# Generated by Django 5.2.5 on 2025-08-29 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tryon', '0003_alter_tryonrequest_prompt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tryonrequest',
            name='body_mask',
        ),
        migrations.RemoveField(
            model_name='tryonrequest',
            name='cloth_image',
        ),
        migrations.RemoveField(
            model_name='tryonrequest',
            name='cloth_mask',
        ),
        migrations.RemoveField(
            model_name='tryonrequest',
            name='generate_from_prompt',
        ),
        migrations.RemoveField(
            model_name='tryonrequest',
            name='pose_json',
        ),
        migrations.AlterField(
            model_name='tryonrequest',
            name='prompt',
            field=models.CharField(default='Default clothing description', max_length=255),
        ),
        migrations.AlterField(
            model_name='tryonrequest',
            name='result_image',
            field=models.ImageField(blank=True, null=True, upload_to='results/'),
        ),
    ]
