# Generated by Django 5.2.5 on 2025-09-03 18:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TryOnResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(help_text='Original user photo', upload_to='uploads/')),
                ('clothing_prompt', models.CharField(help_text='Text description of desired clothing', max_length=500)),
                ('result_image', models.ImageField(blank=True, help_text='Final try-on result', null=True, upload_to='results/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error details if processing failed')),
            ],
            options={
                'verbose_name': 'Try-On Result',
                'verbose_name_plural': 'Try-On Results',
                'ordering': ['-created_at'],
            },
        ),
    ]
